name: dbt Silver Transform

on:
  workflow_dispatch:

jobs:
  dbt-silver:
    name: Run dbt silver model
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Auth to GCP via OIDC
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.DBT_SA }}
          export_environment_variables: true

      - name: Install dbt BigQuery
        run: |
          pip install --upgrade pip
          pip install dbt-bigquery==1.7.9

      - name: Write dbt profiles.yml
        working-directory: dbt
        run: |
          mkdir -p ~/.dbt
          cat > ~/.dbt/profiles.yml <<'EOF'
          insurelytics:
            target: dev
            outputs:
              dev:
                type: bigquery
                method: service-account
                keyfile: "{{ env_var('GOOGLE_GHA_CREDS_PATH') }}"
                project: esg-dev-jahid
                dataset: silver
                location: EU
                threads: 4
                priority: interactive
          EOF

      - name: Run dbt silver
        working-directory: dbt
        run: dbt run --select silver