name: dbt Silver Transform

on:
  workflow_dispatch:

jobs:
  dbt-silver:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write   # required for OIDC

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # Authenticate to GCP via OIDC (no static keys)
      - name: Auth (OIDC → GCP)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/1035645097437/locations/global/workloadIdentityPools/github-pool/providers/github-provider-dppd
          service_account: github-ci-dppd@esg-dev-jahid.iam.gserviceaccount.com
          export_environment_variables: true

      # Some libs look for ADC path — export it to be safe
      - name: Export ADC path
        run: echo "GOOGLE_APPLICATION_CREDENTIALS=$GOOGLE_GHA_CREDS_PATH" >> $GITHUB_ENV

      # (Optional) quick debug of identity/paths
      - name: Who am I? (debug)
        run: |
          gcloud config list account
          echo "GOOGLE_GHA_CREDS_PATH=$GOOGLE_GHA_CREDS_PATH"
          echo "GOOGLE_APPLICATION_CREDENTIALS=$GOOGLE_APPLICATION_CREDENTIALS"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dbt BigQuery
        run: |
          python -m pip install --upgrade pip
          pip install dbt-bigquery==1.7.9

      # Write dbt profiles.yml using the OIDC creds file
      - name: Write dbt profiles.yml
        working-directory: dbt
        run: |
          mkdir -p ~/.dbt
          cat > ~/.dbt/profiles.yml <<'EOF'
          insurelytics:
            target: dev
            outputs:
              dev:
                type: bigquery
                method: service-account
                keyfile: "{{ env_var('GOOGLE_GHA_CREDS_PATH') }}"
                project: esg-dev-jahid
                dataset: silver
                location: EU
                threads: 4
                priority: interactive
          EOF
          echo "---- profiles.yml ----"
          cat ~/.dbt/profiles.yml

      # Run dbt from inside the dbt/ directory so it finds dbt_project.yml
      - name: dbt deps
        working-directory: dbt
        run: dbt deps

      - name: dbt run (silver)
        working-directory: dbt
        run: dbt run --select silver

      - name: dbt test (silver)
        working-directory: dbt
        run: dbt test --select silver