name: terraform-apply

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'terraform/**'
      - '.github/workflows/terraform-apply.yml'

jobs:
  apply:
    runs-on: ubuntu-latest
    environment: prod           # add approvers in GitHub → Settings → Environments
    concurrency:
      group: tf-apply-prod
      cancel-in-progress: false
    permissions:
      contents: read
      id-token: write

    env:
      TF_WORKING_DIR: terraform
      GOOGLE_CLOUD_PROJECT: esg-dev-jahid

    steps:
      - uses: actions/checkout@v4

      - name: Auth (OIDC)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/1035645097437/locations/global/workloadIdentityPools/github-pool/providers/github-provider-dppd
          service_account: github-ci-dppd@esg-dev-jahid.iam.gserviceaccount.com
          export_environment_variables: true

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Clean TF dir
        run: |
          rm -rf "${{ env.TF_WORKING_DIR }}"/.terraform
          rm -f  "${{ env.TF_WORKING_DIR }}"/.terraform.lock.hcl

      - name: Init
        run: terraform -chdir=${{ env.TF_WORKING_DIR }} init -input=false -reconfigure -upgrade

      - name: Plan (confirmation)
        run: terraform -chdir=${{ env.TF_WORKING_DIR }} plan -lock-timeout=120s -input=false -out=tfplan

      - name: Apply (after approval)
        run: terraform -chdir=${{ env.TF_WORKING_DIR }} apply -input=false -auto-approve tfplan

      - name: Show post-apply (human)
        run: terraform -chdir=${{ env.TF_WORKING_DIR }} show -no-color > apply.txt

      - name: List managed resources
        run: terraform -chdir=${{ env.TF_WORKING_DIR }} state list > state-list.txt

      - name: Upload apply artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tfapply-${{ github.run_id }}
          path: |
            ${{ env.TF_WORKING_DIR }}/apply.txt
            ${{ env.TF_WORKING_DIR }}/state-list.txt