name: terraform-apply

on:
  push:
    branches: [ main ]

jobs:
  apply:
    runs-on: ubuntu-latest
    environment: prod
    concurrency: tf-apply-prod
    permissions:
      contents: read
      id-token: write

    env:
      TF_WORKING_DIR: terraform
      GOOGLE_CLOUD_PROJECT: esg-dev-jahid

    steps:
      - uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/1035645097437/locations/global/workloadIdentityPools/github-pool/providers/github-provider-dppd
          service_account: github-ci-dppd@esg-dev-jahid.iam.gserviceaccount.com
          export_environment_variables: true

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - run: terraform -chdir=${{ env.TF_WORKING_DIR }} init -input=false
      - run: terraform -chdir=${{ env.TF_WORKING_DIR }} plan -input=false -out=tfplan
      - run: terraform -chdir=${{ env.TF_WORKING_DIR }} apply -input=false -auto-approve tfplan